name = "LeanCompetLexinon"
version = "0.1.0"
keywords = ["math"]
license = "MIT"
defaultTargets = ["LeanCompetLexinon"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanCompetLexinon"
